# Generated by Django 5.1.2 on 2025-02-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_invitation_unique_email_project_invitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_email_project_invitation',
        ),
    ]
