# Generated by Django 5.1.2 on 2025-01-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='terms',
        ),
    ]
