# Generated by Django 5.1.2 on 2025-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_business_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
