# Generated by Django 5.1.5 on 2025-02-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_meetingroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
    ]
