# Generated by Django 5.1.7 on 2025-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_delete_meetingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
