# Generated by Django 5.1.7 on 2025-04-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_business_category_alter_business_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='slug',
        ),
        migrations.AddField(
            model_name='business',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
