# Generated by Django 5.1.7 on 2025-04-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_remove_business_description_remove_business_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='subdomain',
        ),
    ]
