# Generated by Django 5.1.7 on 2025-04-04 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_remove_business_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.business'),
        ),
    ]
