"""
Django settings for todoapp project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u5q1s7rx3wkrt4cwh%q-zjvkha5pdr$skc5i4a32ksv7=eecb*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'welcome',
    'messaging',
    'projects',
    'businesses',
    'users',
    'tasks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todoapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',  # Ensure this line is included
                'welcome.context_processors.notifications',  # Add our notifications context processor
            ],
        },
    },
]




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'welcome.CustomUser'

STATIC_URL = '/static/'

# Add both the base static directory and the welcome/static directory
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ensure this path is correct
    BASE_DIR / "welcome" / "static",  # Explicitly add welcome/static directory
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'netfull66@gmail.com'
EMAIL_HOST_PASSWORD = 'ggse ugal ocjn babn'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

PAYMOB_API_KEY = 'ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2T1RnNU5qVXlMQ0p1WVcxbElqb2lhVzVwZEdsaGJDSjkuLW9YR2FERDc1SHVnWklYTFJ6WU9Jb202VGRCNk96OXBubTJRT2dITWtrUkNEUWxpQ1VQMlhkMllOeVNMV05YS2JaRUctNEZFOHdnVUREczczcTBZbEE='
PAYMOB_INTEGRATION_ID = '4627071'
PAYMOB_IFRAME_ID = '860965'

ALLOWED_HOSTS = ['netfull.site', '.netfull.site','127.0.0.1']

ROOT_HOSTCONF = 'todoapp.hosts'
DEFAULT_HOST = 'www'

# Maximum size in bytes that will be read from an uploaded file before streaming to storage
FILE_UPLOAD_MAX_MEMORY_SIZE = 512 * 1024  # 512 KB

# Maximum size in bytes of POST data that will be read before streaming
DATA_UPLOAD_MAX_MEMORY_SIZE = 512 * 1024  # 512 KB


STRIPE_PUBLISHABLE_KEY = 'pk_test_51QsVKV06vTQuVgrJcVFlNKRN9cBlchw5Gpeu2r42uihr0v9tNnYuji7a6UlyJLIAs40hGxkHWBkwsmDDf6BgKjRJ00ONcIUteg'
STRIPE_SECRET_KEY = 'sk_test_51QsVKV06vTQuVgrJUYuifZksase2rs0gekwbNKksKhIN1imTUGApIVyy9VewJFHBUK2KBTYJCxNOrTSEiU3DevkI00e7SoDlV2'

# Jitsi Meet Settings
JITSI_APP_ID = "your-jitsi-app-id"  # From Google Cloud Console
JITSI_APP_SECRET = "your-jitsi-app-secret"  # From Google Cloud Console

# OAuth Settings
GOOGLE_CLIENT_ID = "your-google-client-id"
GOOGLE_CLIENT_SECRET = "your-google-client-secret"
GITHUB_CLIENT_ID = "Ov23liU0GfwUWwCelgmd"
GITHUB_CLIENT_SECRET = "065eab0e7620cf854139ef9f4a578a0a346c4a8b"



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'WARNING',  # Only show warnings and errors, not SQL queries
            'handlers': ['console'],
            'propagate': False,
        },
    },
}