# Generated by Django 5.1.2 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_projectresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='penalties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
