# Generated by Django 5.1.4 on 2025-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_userprofile_status_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
