# Generated by Django 5.1.2 on 2025-01-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('welcome', '0006_delete_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='members',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='business',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='business',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='business',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AlterField(
            model_name='prousertask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='ProjectResult',
        ),
        migrations.DeleteModel(
            name='FinanceRecord',
        ),
        migrations.DeleteModel(
            name='CallCenter',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
