# Generated by Django 5.1.2 on 2025-01-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
