# Generated by Django 5.1.2 on 2025-02-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedusertask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prousertask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unloggedusertask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
