# Generated by Django 5.1.2 on 2025-02-07 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('announcement', 'Announcement'), ('message', 'Message'), ('subscription', 'Subscription')], default='info', help_text='The type of the notification (e.g., info, warning, error).', max_length=20)),
                ('message', models.TextField(help_text='The content or message of the notification.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the notification was created.')),
                ('user', models.ForeignKey(help_text='The user who will receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
