# Generated by Django 5.1.2 on 2025-02-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prousertask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
