# Generated by Django 5.1.2 on 2025-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
