# Generated by Django 5.1.2 on 2025-02-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_alter_customuser_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20),
        ),
    ]
