# Generated by Django 5.1.5 on 2025-02-16 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_alter_customuser_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionorder',
            old_name='payment_key',
            new_name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='amount_cents',
            field=models.PositiveIntegerField(help_text='Amount in cents (e.g., $5.00 = 500)'),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
