# Generated by Django 5.1.5 on 2025-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_rename_payment_key_subscriptionorder_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='subscription_type',
            field=models.CharField(choices=[('pro', 'Pro'), ('business', 'Business')], default='pro', max_length=20),
        ),
    ]
