# Generated by Django 5.1.2 on 2025-02-18 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_notification_settings(apps, schema_editor):
    CustomUser = apps.get_model('welcome', 'CustomUser')
    NotificationSettings = apps.get_model('welcome', 'NotificationSettings')
    
    for user in CustomUser.objects.all():
        NotificationSettings.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0018_subscriptionorder_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assignments', models.BooleanField(default=True)),
                ('due_date_reminders', models.BooleanField(default=True)),
                ('task_comments', models.BooleanField(default=True)),
                ('new_projects', models.BooleanField(default=True)),
                ('task_updates', models.BooleanField(default=True)),
                ('role_changes', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('task_completion', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('feature_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_notification_settings),
    ]
