# Generated by Django 5.1.2 on 2025-02-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0019_notificationsettings'),
    ]

    operations = [
    ]
