# Generated by Django 5.1.2 on 2025-02-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0022_featureupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='feature_updates',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='in_app_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='sms_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='task_comments',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='task_updates',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='weekly_summary',
        ),
    ]
