# Generated by Django 5.1.2 on 2025-02-19 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0023_remove_notificationsettings_feature_updates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_fixed', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('sidenav_type', models.CharField(choices=[('bg-gradient-dark', 'Dark'), ('bg-transparent', 'Transparent'), ('bg-white', 'White')], default='bg-white', max_length=50)),
                ('sidebar_color', models.CharField(choices=[('bg-gradient-primary', 'Primary'), ('bg-gradient-dark', 'Dark'), ('bg-gradient-info', 'Info'), ('bg-gradient-success', 'Success'), ('bg-gradient-warning', 'Warning'), ('bg-gradient-danger', 'Danger')], default='bg-gradient-primary', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
